"""empty message

Revision ID: 0b3ae208cd9c
Revises: 30a9bcc5130b
Create Date: 2023-09-02 19:15:08.927049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3ae208cd9c'
down_revision = '30a9bcc5130b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contracts', ['title'])
    op.create_unique_constraint(None, 'projects', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'contracts', type_='unique')
    # ### end Alembic commands ###
